// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: wallet/finance.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Contracts.Wallet {
  public static partial class FinanceService
  {
    static readonly string __ServiceName = "wallet.FinanceService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Contracts.Wallet.SimpleRequest> __Marshaller_wallet_SimpleRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Contracts.Wallet.SimpleRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Contracts.Wallet.GetCategoriesResponse> __Marshaller_wallet_GetCategoriesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Contracts.Wallet.GetCategoriesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Contracts.Wallet.CreateCategoryRequest> __Marshaller_wallet_CreateCategoryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Contracts.Wallet.CreateCategoryRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Contracts.Wallet.SimpleResponse> __Marshaller_wallet_SimpleResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Contracts.Wallet.SimpleResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Contracts.Wallet.UpdateCategoryRequest> __Marshaller_wallet_UpdateCategoryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Contracts.Wallet.UpdateCategoryRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Contracts.Wallet.DeleteRequest> __Marshaller_wallet_DeleteRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Contracts.Wallet.DeleteRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Contracts.Wallet.GetTransactionsResponse> __Marshaller_wallet_GetTransactionsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Contracts.Wallet.GetTransactionsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Contracts.Wallet.CreateTransactionRequest> __Marshaller_wallet_CreateTransactionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Contracts.Wallet.CreateTransactionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Contracts.Wallet.UpdateTransactionRequest> __Marshaller_wallet_UpdateTransactionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Contracts.Wallet.UpdateTransactionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Contracts.Wallet.ExportTransactionsRequest> __Marshaller_wallet_ExportTransactionsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Contracts.Wallet.ExportTransactionsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Contracts.Wallet.ExportTransactionsResponse> __Marshaller_wallet_ExportTransactionsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Contracts.Wallet.ExportTransactionsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Contracts.Wallet.GetTransactionsUpdateHistoryRequest> __Marshaller_wallet_GetTransactionsUpdateHistoryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Contracts.Wallet.GetTransactionsUpdateHistoryRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Contracts.Wallet.GetTransactionsUpdateHistoryResponse> __Marshaller_wallet_GetTransactionsUpdateHistoryResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Contracts.Wallet.GetTransactionsUpdateHistoryResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Contracts.Wallet.SimpleRequest, global::Contracts.Wallet.GetCategoriesResponse> __Method_GetCategories = new grpc::Method<global::Contracts.Wallet.SimpleRequest, global::Contracts.Wallet.GetCategoriesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCategories",
        __Marshaller_wallet_SimpleRequest,
        __Marshaller_wallet_GetCategoriesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Contracts.Wallet.CreateCategoryRequest, global::Contracts.Wallet.SimpleResponse> __Method_CreateCategory = new grpc::Method<global::Contracts.Wallet.CreateCategoryRequest, global::Contracts.Wallet.SimpleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateCategory",
        __Marshaller_wallet_CreateCategoryRequest,
        __Marshaller_wallet_SimpleResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Contracts.Wallet.UpdateCategoryRequest, global::Contracts.Wallet.SimpleResponse> __Method_UpdateCategory = new grpc::Method<global::Contracts.Wallet.UpdateCategoryRequest, global::Contracts.Wallet.SimpleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateCategory",
        __Marshaller_wallet_UpdateCategoryRequest,
        __Marshaller_wallet_SimpleResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Contracts.Wallet.DeleteRequest, global::Contracts.Wallet.SimpleResponse> __Method_DeleteCategory = new grpc::Method<global::Contracts.Wallet.DeleteRequest, global::Contracts.Wallet.SimpleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteCategory",
        __Marshaller_wallet_DeleteRequest,
        __Marshaller_wallet_SimpleResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Contracts.Wallet.SimpleRequest, global::Contracts.Wallet.GetTransactionsResponse> __Method_GetTransactions = new grpc::Method<global::Contracts.Wallet.SimpleRequest, global::Contracts.Wallet.GetTransactionsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTransactions",
        __Marshaller_wallet_SimpleRequest,
        __Marshaller_wallet_GetTransactionsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Contracts.Wallet.CreateTransactionRequest, global::Contracts.Wallet.SimpleResponse> __Method_CreateTransaction = new grpc::Method<global::Contracts.Wallet.CreateTransactionRequest, global::Contracts.Wallet.SimpleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateTransaction",
        __Marshaller_wallet_CreateTransactionRequest,
        __Marshaller_wallet_SimpleResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Contracts.Wallet.UpdateTransactionRequest, global::Contracts.Wallet.SimpleResponse> __Method_UpdateTransaction = new grpc::Method<global::Contracts.Wallet.UpdateTransactionRequest, global::Contracts.Wallet.SimpleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateTransaction",
        __Marshaller_wallet_UpdateTransactionRequest,
        __Marshaller_wallet_SimpleResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Contracts.Wallet.DeleteRequest, global::Contracts.Wallet.SimpleResponse> __Method_DeleteTransaction = new grpc::Method<global::Contracts.Wallet.DeleteRequest, global::Contracts.Wallet.SimpleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteTransaction",
        __Marshaller_wallet_DeleteRequest,
        __Marshaller_wallet_SimpleResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Contracts.Wallet.ExportTransactionsRequest, global::Contracts.Wallet.ExportTransactionsResponse> __Method_ExportTransactions = new grpc::Method<global::Contracts.Wallet.ExportTransactionsRequest, global::Contracts.Wallet.ExportTransactionsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ExportTransactions",
        __Marshaller_wallet_ExportTransactionsRequest,
        __Marshaller_wallet_ExportTransactionsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Contracts.Wallet.GetTransactionsUpdateHistoryRequest, global::Contracts.Wallet.GetTransactionsUpdateHistoryResponse> __Method_GetTransactionsUpdateHistory = new grpc::Method<global::Contracts.Wallet.GetTransactionsUpdateHistoryRequest, global::Contracts.Wallet.GetTransactionsUpdateHistoryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTransactionsUpdateHistory",
        __Marshaller_wallet_GetTransactionsUpdateHistoryRequest,
        __Marshaller_wallet_GetTransactionsUpdateHistoryResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Contracts.Wallet.FinanceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FinanceService</summary>
    [grpc::BindServiceMethod(typeof(FinanceService), "BindService")]
    public abstract partial class FinanceServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Contracts.Wallet.GetCategoriesResponse> GetCategories(global::Contracts.Wallet.SimpleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Contracts.Wallet.SimpleResponse> CreateCategory(global::Contracts.Wallet.CreateCategoryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Contracts.Wallet.SimpleResponse> UpdateCategory(global::Contracts.Wallet.UpdateCategoryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Contracts.Wallet.SimpleResponse> DeleteCategory(global::Contracts.Wallet.DeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Contracts.Wallet.GetTransactionsResponse> GetTransactions(global::Contracts.Wallet.SimpleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Contracts.Wallet.SimpleResponse> CreateTransaction(global::Contracts.Wallet.CreateTransactionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Contracts.Wallet.SimpleResponse> UpdateTransaction(global::Contracts.Wallet.UpdateTransactionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Contracts.Wallet.SimpleResponse> DeleteTransaction(global::Contracts.Wallet.DeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Contracts.Wallet.ExportTransactionsResponse> ExportTransactions(global::Contracts.Wallet.ExportTransactionsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Contracts.Wallet.GetTransactionsUpdateHistoryResponse> GetTransactionsUpdateHistory(global::Contracts.Wallet.GetTransactionsUpdateHistoryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FinanceService</summary>
    public partial class FinanceServiceClient : grpc::ClientBase<FinanceServiceClient>
    {
      /// <summary>Creates a new client for FinanceService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public FinanceServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FinanceService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public FinanceServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected FinanceServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected FinanceServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.GetCategoriesResponse GetCategories(global::Contracts.Wallet.SimpleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCategories(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.GetCategoriesResponse GetCategories(global::Contracts.Wallet.SimpleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCategories, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.GetCategoriesResponse> GetCategoriesAsync(global::Contracts.Wallet.SimpleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCategoriesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.GetCategoriesResponse> GetCategoriesAsync(global::Contracts.Wallet.SimpleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCategories, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.SimpleResponse CreateCategory(global::Contracts.Wallet.CreateCategoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateCategory(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.SimpleResponse CreateCategory(global::Contracts.Wallet.CreateCategoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateCategory, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.SimpleResponse> CreateCategoryAsync(global::Contracts.Wallet.CreateCategoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateCategoryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.SimpleResponse> CreateCategoryAsync(global::Contracts.Wallet.CreateCategoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateCategory, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.SimpleResponse UpdateCategory(global::Contracts.Wallet.UpdateCategoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateCategory(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.SimpleResponse UpdateCategory(global::Contracts.Wallet.UpdateCategoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateCategory, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.SimpleResponse> UpdateCategoryAsync(global::Contracts.Wallet.UpdateCategoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateCategoryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.SimpleResponse> UpdateCategoryAsync(global::Contracts.Wallet.UpdateCategoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateCategory, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.SimpleResponse DeleteCategory(global::Contracts.Wallet.DeleteRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteCategory(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.SimpleResponse DeleteCategory(global::Contracts.Wallet.DeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteCategory, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.SimpleResponse> DeleteCategoryAsync(global::Contracts.Wallet.DeleteRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteCategoryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.SimpleResponse> DeleteCategoryAsync(global::Contracts.Wallet.DeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteCategory, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.GetTransactionsResponse GetTransactions(global::Contracts.Wallet.SimpleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTransactions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.GetTransactionsResponse GetTransactions(global::Contracts.Wallet.SimpleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTransactions, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.GetTransactionsResponse> GetTransactionsAsync(global::Contracts.Wallet.SimpleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTransactionsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.GetTransactionsResponse> GetTransactionsAsync(global::Contracts.Wallet.SimpleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTransactions, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.SimpleResponse CreateTransaction(global::Contracts.Wallet.CreateTransactionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateTransaction(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.SimpleResponse CreateTransaction(global::Contracts.Wallet.CreateTransactionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateTransaction, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.SimpleResponse> CreateTransactionAsync(global::Contracts.Wallet.CreateTransactionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateTransactionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.SimpleResponse> CreateTransactionAsync(global::Contracts.Wallet.CreateTransactionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateTransaction, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.SimpleResponse UpdateTransaction(global::Contracts.Wallet.UpdateTransactionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateTransaction(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.SimpleResponse UpdateTransaction(global::Contracts.Wallet.UpdateTransactionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateTransaction, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.SimpleResponse> UpdateTransactionAsync(global::Contracts.Wallet.UpdateTransactionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateTransactionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.SimpleResponse> UpdateTransactionAsync(global::Contracts.Wallet.UpdateTransactionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateTransaction, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.SimpleResponse DeleteTransaction(global::Contracts.Wallet.DeleteRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteTransaction(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.SimpleResponse DeleteTransaction(global::Contracts.Wallet.DeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteTransaction, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.SimpleResponse> DeleteTransactionAsync(global::Contracts.Wallet.DeleteRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteTransactionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.SimpleResponse> DeleteTransactionAsync(global::Contracts.Wallet.DeleteRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteTransaction, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.ExportTransactionsResponse ExportTransactions(global::Contracts.Wallet.ExportTransactionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExportTransactions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.ExportTransactionsResponse ExportTransactions(global::Contracts.Wallet.ExportTransactionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ExportTransactions, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.ExportTransactionsResponse> ExportTransactionsAsync(global::Contracts.Wallet.ExportTransactionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExportTransactionsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.ExportTransactionsResponse> ExportTransactionsAsync(global::Contracts.Wallet.ExportTransactionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ExportTransactions, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.GetTransactionsUpdateHistoryResponse GetTransactionsUpdateHistory(global::Contracts.Wallet.GetTransactionsUpdateHistoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTransactionsUpdateHistory(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Contracts.Wallet.GetTransactionsUpdateHistoryResponse GetTransactionsUpdateHistory(global::Contracts.Wallet.GetTransactionsUpdateHistoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTransactionsUpdateHistory, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.GetTransactionsUpdateHistoryResponse> GetTransactionsUpdateHistoryAsync(global::Contracts.Wallet.GetTransactionsUpdateHistoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTransactionsUpdateHistoryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Contracts.Wallet.GetTransactionsUpdateHistoryResponse> GetTransactionsUpdateHistoryAsync(global::Contracts.Wallet.GetTransactionsUpdateHistoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTransactionsUpdateHistory, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override FinanceServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FinanceServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(FinanceServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetCategories, serviceImpl.GetCategories)
          .AddMethod(__Method_CreateCategory, serviceImpl.CreateCategory)
          .AddMethod(__Method_UpdateCategory, serviceImpl.UpdateCategory)
          .AddMethod(__Method_DeleteCategory, serviceImpl.DeleteCategory)
          .AddMethod(__Method_GetTransactions, serviceImpl.GetTransactions)
          .AddMethod(__Method_CreateTransaction, serviceImpl.CreateTransaction)
          .AddMethod(__Method_UpdateTransaction, serviceImpl.UpdateTransaction)
          .AddMethod(__Method_DeleteTransaction, serviceImpl.DeleteTransaction)
          .AddMethod(__Method_ExportTransactions, serviceImpl.ExportTransactions)
          .AddMethod(__Method_GetTransactionsUpdateHistory, serviceImpl.GetTransactionsUpdateHistory).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, FinanceServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetCategories, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Contracts.Wallet.SimpleRequest, global::Contracts.Wallet.GetCategoriesResponse>(serviceImpl.GetCategories));
      serviceBinder.AddMethod(__Method_CreateCategory, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Contracts.Wallet.CreateCategoryRequest, global::Contracts.Wallet.SimpleResponse>(serviceImpl.CreateCategory));
      serviceBinder.AddMethod(__Method_UpdateCategory, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Contracts.Wallet.UpdateCategoryRequest, global::Contracts.Wallet.SimpleResponse>(serviceImpl.UpdateCategory));
      serviceBinder.AddMethod(__Method_DeleteCategory, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Contracts.Wallet.DeleteRequest, global::Contracts.Wallet.SimpleResponse>(serviceImpl.DeleteCategory));
      serviceBinder.AddMethod(__Method_GetTransactions, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Contracts.Wallet.SimpleRequest, global::Contracts.Wallet.GetTransactionsResponse>(serviceImpl.GetTransactions));
      serviceBinder.AddMethod(__Method_CreateTransaction, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Contracts.Wallet.CreateTransactionRequest, global::Contracts.Wallet.SimpleResponse>(serviceImpl.CreateTransaction));
      serviceBinder.AddMethod(__Method_UpdateTransaction, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Contracts.Wallet.UpdateTransactionRequest, global::Contracts.Wallet.SimpleResponse>(serviceImpl.UpdateTransaction));
      serviceBinder.AddMethod(__Method_DeleteTransaction, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Contracts.Wallet.DeleteRequest, global::Contracts.Wallet.SimpleResponse>(serviceImpl.DeleteTransaction));
      serviceBinder.AddMethod(__Method_ExportTransactions, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Contracts.Wallet.ExportTransactionsRequest, global::Contracts.Wallet.ExportTransactionsResponse>(serviceImpl.ExportTransactions));
      serviceBinder.AddMethod(__Method_GetTransactionsUpdateHistory, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Contracts.Wallet.GetTransactionsUpdateHistoryRequest, global::Contracts.Wallet.GetTransactionsUpdateHistoryResponse>(serviceImpl.GetTransactionsUpdateHistory));
    }

  }
}
#endregion
