// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: wallet/user.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Contracts.Wallet {

  /// <summary>Holder for reflection information generated from wallet/user.proto</summary>
  public static partial class UserReflection {

    #region Descriptor
    /// <summary>File descriptor for wallet/user.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChF3YWxsZXQvdXNlci5wcm90bxIGd2FsbGV0Ghlnb29nbGUvdHlwZS9kZWNp",
            "bWFsLnByb3RvGhN3YWxsZXQvY29tbW9uLnByb3RvIpcCChZHZXRVc2VyU3Vt",
            "bWFyeVJlc3BvbnNlEjMKCmFsbF9pbmNvbWUYASABKAsyFC5nb29nbGUudHlw",
            "ZS5EZWNpbWFsUglhbGxJbmNvbWUSNQoLYWxsX2V4cGVuc2UYAiABKAsyFC5n",
            "b29nbGUudHlwZS5EZWNpbWFsUgphbGxFeHBlbnNlEjcKDG1vbnRoX2luY29t",
            "ZRgDIAEoCzIULmdvb2dsZS50eXBlLkRlY2ltYWxSC21vbnRoSW5jb21lEjkK",
            "DW1vbnRoX2V4cGVuc2UYBCABKAsyFC5nb29nbGUudHlwZS5EZWNpbWFsUgxt",
            "b250aEV4cGVuc2USHQoKc3RhcnRfZGF0ZRgFIAEoCVIJc3RhcnREYXRlMlYK",
            "C1VzZXJTZXJ2aWNlEkcKDkdldFVzZXJTdW1tYXJ5EhUud2FsbGV0LlNpbXBs",
            "ZVJlcXVlc3QaHi53YWxsZXQuR2V0VXNlclN1bW1hcnlSZXNwb25zZUKTAQoK",
            "Y29tLndhbGxldEIJVXNlclByb3RvUAFaOGdpdGh1Yi5jb20vQWRpdHlhLTAw",
            "MTEvY29tbW9uL2NvbnRyYWN0cy9nby93YWxsZXQ7d2FsbGV0ogIDV1hYqgIQ",
            "Q29udHJhY3RzLldhbGxldMoCBldhbGxldOICEldhbGxldFxHUEJNZXRhZGF0",
            "YeoCBldhbGxldGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Type.DecimalReflection.Descriptor, global::Contracts.Wallet.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Contracts.Wallet.GetUserSummaryResponse), global::Contracts.Wallet.GetUserSummaryResponse.Parser, new[]{ "AllIncome", "AllExpense", "MonthIncome", "MonthExpense", "StartDate" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetUserSummaryResponse : pb::IMessage<GetUserSummaryResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetUserSummaryResponse> _parser = new pb::MessageParser<GetUserSummaryResponse>(() => new GetUserSummaryResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetUserSummaryResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Contracts.Wallet.UserReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetUserSummaryResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetUserSummaryResponse(GetUserSummaryResponse other) : this() {
      allIncome_ = other.allIncome_ != null ? other.allIncome_.Clone() : null;
      allExpense_ = other.allExpense_ != null ? other.allExpense_.Clone() : null;
      monthIncome_ = other.monthIncome_ != null ? other.monthIncome_.Clone() : null;
      monthExpense_ = other.monthExpense_ != null ? other.monthExpense_.Clone() : null;
      startDate_ = other.startDate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetUserSummaryResponse Clone() {
      return new GetUserSummaryResponse(this);
    }

    /// <summary>Field number for the "all_income" field.</summary>
    public const int AllIncomeFieldNumber = 1;
    private global::Google.Type.Decimal allIncome_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Decimal AllIncome {
      get { return allIncome_; }
      set {
        allIncome_ = value;
      }
    }

    /// <summary>Field number for the "all_expense" field.</summary>
    public const int AllExpenseFieldNumber = 2;
    private global::Google.Type.Decimal allExpense_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Decimal AllExpense {
      get { return allExpense_; }
      set {
        allExpense_ = value;
      }
    }

    /// <summary>Field number for the "month_income" field.</summary>
    public const int MonthIncomeFieldNumber = 3;
    private global::Google.Type.Decimal monthIncome_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Decimal MonthIncome {
      get { return monthIncome_; }
      set {
        monthIncome_ = value;
      }
    }

    /// <summary>Field number for the "month_expense" field.</summary>
    public const int MonthExpenseFieldNumber = 4;
    private global::Google.Type.Decimal monthExpense_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Type.Decimal MonthExpense {
      get { return monthExpense_; }
      set {
        monthExpense_ = value;
      }
    }

    /// <summary>Field number for the "start_date" field.</summary>
    public const int StartDateFieldNumber = 5;
    private string startDate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StartDate {
      get { return startDate_; }
      set {
        startDate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetUserSummaryResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetUserSummaryResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AllIncome, other.AllIncome)) return false;
      if (!object.Equals(AllExpense, other.AllExpense)) return false;
      if (!object.Equals(MonthIncome, other.MonthIncome)) return false;
      if (!object.Equals(MonthExpense, other.MonthExpense)) return false;
      if (StartDate != other.StartDate) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (allIncome_ != null) hash ^= AllIncome.GetHashCode();
      if (allExpense_ != null) hash ^= AllExpense.GetHashCode();
      if (monthIncome_ != null) hash ^= MonthIncome.GetHashCode();
      if (monthExpense_ != null) hash ^= MonthExpense.GetHashCode();
      if (StartDate.Length != 0) hash ^= StartDate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (allIncome_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AllIncome);
      }
      if (allExpense_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AllExpense);
      }
      if (monthIncome_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MonthIncome);
      }
      if (monthExpense_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(MonthExpense);
      }
      if (StartDate.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(StartDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (allIncome_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AllIncome);
      }
      if (allExpense_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AllExpense);
      }
      if (monthIncome_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MonthIncome);
      }
      if (monthExpense_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(MonthExpense);
      }
      if (StartDate.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(StartDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (allIncome_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AllIncome);
      }
      if (allExpense_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AllExpense);
      }
      if (monthIncome_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MonthIncome);
      }
      if (monthExpense_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MonthExpense);
      }
      if (StartDate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StartDate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetUserSummaryResponse other) {
      if (other == null) {
        return;
      }
      if (other.allIncome_ != null) {
        if (allIncome_ == null) {
          AllIncome = new global::Google.Type.Decimal();
        }
        AllIncome.MergeFrom(other.AllIncome);
      }
      if (other.allExpense_ != null) {
        if (allExpense_ == null) {
          AllExpense = new global::Google.Type.Decimal();
        }
        AllExpense.MergeFrom(other.AllExpense);
      }
      if (other.monthIncome_ != null) {
        if (monthIncome_ == null) {
          MonthIncome = new global::Google.Type.Decimal();
        }
        MonthIncome.MergeFrom(other.MonthIncome);
      }
      if (other.monthExpense_ != null) {
        if (monthExpense_ == null) {
          MonthExpense = new global::Google.Type.Decimal();
        }
        MonthExpense.MergeFrom(other.MonthExpense);
      }
      if (other.StartDate.Length != 0) {
        StartDate = other.StartDate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (allIncome_ == null) {
              AllIncome = new global::Google.Type.Decimal();
            }
            input.ReadMessage(AllIncome);
            break;
          }
          case 18: {
            if (allExpense_ == null) {
              AllExpense = new global::Google.Type.Decimal();
            }
            input.ReadMessage(AllExpense);
            break;
          }
          case 26: {
            if (monthIncome_ == null) {
              MonthIncome = new global::Google.Type.Decimal();
            }
            input.ReadMessage(MonthIncome);
            break;
          }
          case 34: {
            if (monthExpense_ == null) {
              MonthExpense = new global::Google.Type.Decimal();
            }
            input.ReadMessage(MonthExpense);
            break;
          }
          case 42: {
            StartDate = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (allIncome_ == null) {
              AllIncome = new global::Google.Type.Decimal();
            }
            input.ReadMessage(AllIncome);
            break;
          }
          case 18: {
            if (allExpense_ == null) {
              AllExpense = new global::Google.Type.Decimal();
            }
            input.ReadMessage(AllExpense);
            break;
          }
          case 26: {
            if (monthIncome_ == null) {
              MonthIncome = new global::Google.Type.Decimal();
            }
            input.ReadMessage(MonthIncome);
            break;
          }
          case 34: {
            if (monthExpense_ == null) {
              MonthExpense = new global::Google.Type.Decimal();
            }
            input.ReadMessage(MonthExpense);
            break;
          }
          case 42: {
            StartDate = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
