// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: portfolio.proto

package manager

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TechnologyCategory int32

const (
	TechnologyCategory_TECHNOLOGY_CATEGORY_UNSPECIFIED TechnologyCategory = 0
	TechnologyCategory_TECHNOLOGY_CATEGORY_FRONTEND    TechnologyCategory = 1
	TechnologyCategory_TECHNOLOGY_CATEGORY_BACKEND     TechnologyCategory = 2
	TechnologyCategory_TECHNOLOGY_CATEGORY_DB          TechnologyCategory = 3
	TechnologyCategory_TECHNOLOGY_CATEGORY_LANGUAGE    TechnologyCategory = 4
	TechnologyCategory_TECHNOLOGY_CATEGORY_TOOL        TechnologyCategory = 5
	TechnologyCategory_TECHNOLOGY_CATEGORY_ACADEMICS   TechnologyCategory = 6
	TechnologyCategory_TECHNOLOGY_CATEGORY_NONE        TechnologyCategory = 7
)

// Enum value maps for TechnologyCategory.
var (
	TechnologyCategory_name = map[int32]string{
		0: "TECHNOLOGY_CATEGORY_UNSPECIFIED",
		1: "TECHNOLOGY_CATEGORY_FRONTEND",
		2: "TECHNOLOGY_CATEGORY_BACKEND",
		3: "TECHNOLOGY_CATEGORY_DB",
		4: "TECHNOLOGY_CATEGORY_LANGUAGE",
		5: "TECHNOLOGY_CATEGORY_TOOL",
		6: "TECHNOLOGY_CATEGORY_ACADEMICS",
		7: "TECHNOLOGY_CATEGORY_NONE",
	}
	TechnologyCategory_value = map[string]int32{
		"TECHNOLOGY_CATEGORY_UNSPECIFIED": 0,
		"TECHNOLOGY_CATEGORY_FRONTEND":    1,
		"TECHNOLOGY_CATEGORY_BACKEND":     2,
		"TECHNOLOGY_CATEGORY_DB":          3,
		"TECHNOLOGY_CATEGORY_LANGUAGE":    4,
		"TECHNOLOGY_CATEGORY_TOOL":        5,
		"TECHNOLOGY_CATEGORY_ACADEMICS":   6,
		"TECHNOLOGY_CATEGORY_NONE":        7,
	}
)

func (x TechnologyCategory) Enum() *TechnologyCategory {
	p := new(TechnologyCategory)
	*p = x
	return p
}

func (x TechnologyCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TechnologyCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_portfolio_proto_enumTypes[0].Descriptor()
}

func (TechnologyCategory) Type() protoreflect.EnumType {
	return &file_portfolio_proto_enumTypes[0]
}

func (x TechnologyCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TechnologyCategory.Descriptor instead.
func (TechnologyCategory) EnumDescriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{0}
}

type Technology struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	FallbackImageUrl string                 `protobuf:"bytes,4,opt,name=fallback_image_url,json=fallbackImageUrl,proto3" json:"fallback_image_url,omitempty"`
	Category         TechnologyCategory     `protobuf:"varint,5,opt,name=category,proto3,enum=manager.TechnologyCategory" json:"category,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Technology) Reset() {
	*x = Technology{}
	mi := &file_portfolio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Technology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Technology) ProtoMessage() {}

func (x *Technology) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Technology.ProtoReflect.Descriptor instead.
func (*Technology) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{0}
}

func (x *Technology) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Technology) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Technology) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Technology) GetFallbackImageUrl() string {
	if x != nil {
		return x.FallbackImageUrl
	}
	return ""
}

func (x *Technology) GetCategory() TechnologyCategory {
	if x != nil {
		return x.Category
	}
	return TechnologyCategory_TECHNOLOGY_CATEGORY_UNSPECIFIED
}

func (x *Technology) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TechnologySummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	FallbackImageUrl string                 `protobuf:"bytes,4,opt,name=fallback_image_url,json=fallbackImageUrl,proto3" json:"fallback_image_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TechnologySummary) Reset() {
	*x = TechnologySummary{}
	mi := &file_portfolio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TechnologySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TechnologySummary) ProtoMessage() {}

func (x *TechnologySummary) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TechnologySummary.ProtoReflect.Descriptor instead.
func (*TechnologySummary) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{1}
}

func (x *TechnologySummary) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TechnologySummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TechnologySummary) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *TechnologySummary) GetFallbackImageUrl() string {
	if x != nil {
		return x.FallbackImageUrl
	}
	return ""
}

type GetTechnologiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Technologies  []*Technology          `protobuf:"bytes,1,rep,name=technologies,proto3" json:"technologies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTechnologiesResponse) Reset() {
	*x = GetTechnologiesResponse{}
	mi := &file_portfolio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTechnologiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTechnologiesResponse) ProtoMessage() {}

func (x *GetTechnologiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTechnologiesResponse.ProtoReflect.Descriptor instead.
func (*GetTechnologiesResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{2}
}

func (x *GetTechnologiesResponse) GetTechnologies() []*Technology {
	if x != nil {
		return x.Technologies
	}
	return nil
}

type TechnologyCreateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	FallbackImageUrl string                 `protobuf:"bytes,4,opt,name=fallback_image_url,json=fallbackImageUrl,proto3" json:"fallback_image_url,omitempty"`
	Category         TechnologyCategory     `protobuf:"varint,5,opt,name=category,proto3,enum=manager.TechnologyCategory" json:"category,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TechnologyCreateRequest) Reset() {
	*x = TechnologyCreateRequest{}
	mi := &file_portfolio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TechnologyCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TechnologyCreateRequest) ProtoMessage() {}

func (x *TechnologyCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TechnologyCreateRequest.ProtoReflect.Descriptor instead.
func (*TechnologyCreateRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{3}
}

func (x *TechnologyCreateRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TechnologyCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TechnologyCreateRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *TechnologyCreateRequest) GetFallbackImageUrl() string {
	if x != nil {
		return x.FallbackImageUrl
	}
	return ""
}

func (x *TechnologyCreateRequest) GetCategory() TechnologyCategory {
	if x != nil {
		return x.Category
	}
	return TechnologyCategory_TECHNOLOGY_CATEGORY_UNSPECIFIED
}

type TechnologyUpdateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id               int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	FallbackImageUrl string                 `protobuf:"bytes,5,opt,name=fallback_image_url,json=fallbackImageUrl,proto3" json:"fallback_image_url,omitempty"`
	Category         TechnologyCategory     `protobuf:"varint,6,opt,name=category,proto3,enum=manager.TechnologyCategory" json:"category,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TechnologyUpdateRequest) Reset() {
	*x = TechnologyUpdateRequest{}
	mi := &file_portfolio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TechnologyUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TechnologyUpdateRequest) ProtoMessage() {}

func (x *TechnologyUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TechnologyUpdateRequest.ProtoReflect.Descriptor instead.
func (*TechnologyUpdateRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{4}
}

func (x *TechnologyUpdateRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TechnologyUpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TechnologyUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TechnologyUpdateRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *TechnologyUpdateRequest) GetFallbackImageUrl() string {
	if x != nil {
		return x.FallbackImageUrl
	}
	return ""
}

func (x *TechnologyUpdateRequest) GetCategory() TechnologyCategory {
	if x != nil {
		return x.Category
	}
	return TechnologyCategory_TECHNOLOGY_CATEGORY_UNSPECIFIED
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ProjectUrl    *string                `protobuf:"bytes,5,opt,name=project_url,json=projectUrl,proto3,oneof" json:"project_url,omitempty"`
	GithubUrl     *string                `protobuf:"bytes,6,opt,name=github_url,json=githubUrl,proto3,oneof" json:"github_url,omitempty"`
	Technologies  []*TechnologySummary   `protobuf:"bytes,7,rep,name=technologies,proto3" json:"technologies,omitempty"`
	Featured      bool                   `protobuf:"varint,8,opt,name=featured,proto3" json:"featured,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_portfolio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{5}
}

func (x *Project) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Project) GetProjectUrl() string {
	if x != nil && x.ProjectUrl != nil {
		return *x.ProjectUrl
	}
	return ""
}

func (x *Project) GetGithubUrl() string {
	if x != nil && x.GithubUrl != nil {
		return *x.GithubUrl
	}
	return ""
}

func (x *Project) GetTechnologies() []*TechnologySummary {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *Project) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

func (x *Project) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProjectSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectSummary) Reset() {
	*x = ProjectSummary{}
	mi := &file_portfolio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSummary) ProtoMessage() {}

func (x *ProjectSummary) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSummary.ProtoReflect.Descriptor instead.
func (*ProjectSummary) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectSummary) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectsResponse) Reset() {
	*x = GetProjectsResponse{}
	mi := &file_portfolio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectsResponse) ProtoMessage() {}

func (x *GetProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectsResponse.ProtoReflect.Descriptor instead.
func (*GetProjectsResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{7}
}

func (x *GetProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type ProjectCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ProjectUrl    *string                `protobuf:"bytes,5,opt,name=project_url,json=projectUrl,proto3,oneof" json:"project_url,omitempty"`
	GithubUrl     *string                `protobuf:"bytes,6,opt,name=github_url,json=githubUrl,proto3,oneof" json:"github_url,omitempty"`
	Technologies  []int32                `protobuf:"varint,7,rep,packed,name=technologies,proto3" json:"technologies,omitempty"`
	Featured      bool                   `protobuf:"varint,8,opt,name=featured,proto3" json:"featured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectCreateRequest) Reset() {
	*x = ProjectCreateRequest{}
	mi := &file_portfolio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCreateRequest) ProtoMessage() {}

func (x *ProjectCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCreateRequest.ProtoReflect.Descriptor instead.
func (*ProjectCreateRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectCreateRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProjectCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectCreateRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ProjectCreateRequest) GetProjectUrl() string {
	if x != nil && x.ProjectUrl != nil {
		return *x.ProjectUrl
	}
	return ""
}

func (x *ProjectCreateRequest) GetGithubUrl() string {
	if x != nil && x.GithubUrl != nil {
		return *x.GithubUrl
	}
	return ""
}

func (x *ProjectCreateRequest) GetTechnologies() []int32 {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *ProjectCreateRequest) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

type ProjectUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ProjectUrl    *string                `protobuf:"bytes,6,opt,name=project_url,json=projectUrl,proto3,oneof" json:"project_url,omitempty"`
	GithubUrl     *string                `protobuf:"bytes,7,opt,name=github_url,json=githubUrl,proto3,oneof" json:"github_url,omitempty"`
	Technologies  []int32                `protobuf:"varint,8,rep,packed,name=technologies,proto3" json:"technologies,omitempty"`
	Featured      bool                   `protobuf:"varint,9,opt,name=featured,proto3" json:"featured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectUpdateRequest) Reset() {
	*x = ProjectUpdateRequest{}
	mi := &file_portfolio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectUpdateRequest) ProtoMessage() {}

func (x *ProjectUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProjectUpdateRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectUpdateRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProjectUpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProjectUpdateRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ProjectUpdateRequest) GetProjectUrl() string {
	if x != nil && x.ProjectUrl != nil {
		return *x.ProjectUrl
	}
	return ""
}

func (x *ProjectUpdateRequest) GetGithubUrl() string {
	if x != nil && x.GithubUrl != nil {
		return *x.GithubUrl
	}
	return ""
}

func (x *ProjectUpdateRequest) GetTechnologies() []int32 {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *ProjectUpdateRequest) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Start         string                 `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	WorkDone      string                 `protobuf:"bytes,5,opt,name=work_done,json=workDone,proto3" json:"work_done,omitempty"`
	Projects      []*ProjectSummary      `protobuf:"bytes,6,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_portfolio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{10}
}

func (x *Position) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Position) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Position) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Position) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *Position) GetWorkDone() string {
	if x != nil {
		return x.WorkDone
	}
	return ""
}

func (x *Position) GetProjects() []*ProjectSummary {
	if x != nil {
		return x.Projects
	}
	return nil
}

type PositionCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Start         string                 `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           *string                `protobuf:"bytes,4,opt,name=end,proto3,oneof" json:"end,omitempty"`
	WorkDone      string                 `protobuf:"bytes,5,opt,name=work_done,json=workDone,proto3" json:"work_done,omitempty"`
	Projects      []int32                `protobuf:"varint,6,rep,packed,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionCreate) Reset() {
	*x = PositionCreate{}
	mi := &file_portfolio_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionCreate) ProtoMessage() {}

func (x *PositionCreate) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionCreate.ProtoReflect.Descriptor instead.
func (*PositionCreate) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{11}
}

func (x *PositionCreate) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PositionCreate) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PositionCreate) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *PositionCreate) GetEnd() string {
	if x != nil && x.End != nil {
		return *x.End
	}
	return ""
}

func (x *PositionCreate) GetWorkDone() string {
	if x != nil {
		return x.WorkDone
	}
	return ""
}

func (x *PositionCreate) GetProjects() []int32 {
	if x != nil {
		return x.Projects
	}
	return nil
}

type PositionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	NewId         *string                `protobuf:"bytes,3,opt,name=new_id,json=newId,proto3,oneof" json:"new_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Start         string                 `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	End           *string                `protobuf:"bytes,6,opt,name=end,proto3,oneof" json:"end,omitempty"`
	WorkDone      string                 `protobuf:"bytes,7,opt,name=work_done,json=workDone,proto3" json:"work_done,omitempty"`
	Projects      []int32                `protobuf:"varint,8,rep,packed,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionUpdate) Reset() {
	*x = PositionUpdate{}
	mi := &file_portfolio_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionUpdate) ProtoMessage() {}

func (x *PositionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionUpdate.ProtoReflect.Descriptor instead.
func (*PositionUpdate) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{12}
}

func (x *PositionUpdate) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PositionUpdate) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PositionUpdate) GetNewId() string {
	if x != nil && x.NewId != nil {
		return *x.NewId
	}
	return ""
}

func (x *PositionUpdate) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PositionUpdate) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *PositionUpdate) GetEnd() string {
	if x != nil && x.End != nil {
		return *x.End
	}
	return ""
}

func (x *PositionUpdate) GetWorkDone() string {
	if x != nil {
		return x.WorkDone
	}
	return ""
}

func (x *PositionUpdate) GetProjects() []int32 {
	if x != nil {
		return x.Projects
	}
	return nil
}

type Experience struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Company       string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Start         string                 `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End           string                 `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	Tenure        string                 `protobuf:"bytes,5,opt,name=tenure,proto3" json:"tenure,omitempty"`
	Positions     []*Position            `protobuf:"bytes,6,rep,name=positions,proto3" json:"positions,omitempty"`
	Technologies  []*TechnologySummary   `protobuf:"bytes,7,rep,name=technologies,proto3" json:"technologies,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Experience) Reset() {
	*x = Experience{}
	mi := &file_portfolio_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Experience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experience) ProtoMessage() {}

func (x *Experience) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experience.ProtoReflect.Descriptor instead.
func (*Experience) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{13}
}

func (x *Experience) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Experience) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Experience) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *Experience) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *Experience) GetTenure() string {
	if x != nil {
		return x.Tenure
	}
	return ""
}

func (x *Experience) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *Experience) GetTechnologies() []*TechnologySummary {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *Experience) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetExperiencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Experiences   []*Experience          `protobuf:"bytes,1,rep,name=experiences,proto3" json:"experiences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExperiencesResponse) Reset() {
	*x = GetExperiencesResponse{}
	mi := &file_portfolio_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExperiencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExperiencesResponse) ProtoMessage() {}

func (x *GetExperiencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExperiencesResponse.ProtoReflect.Descriptor instead.
func (*GetExperiencesResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{14}
}

func (x *GetExperiencesResponse) GetExperiences() []*Experience {
	if x != nil {
		return x.Experiences
	}
	return nil
}

type ExperienceCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Positions     []*PositionCreate      `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	Technologies  []int32                `protobuf:"varint,4,rep,packed,name=technologies,proto3" json:"technologies,omitempty"`
	Company       string                 `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperienceCreateRequest) Reset() {
	*x = ExperienceCreateRequest{}
	mi := &file_portfolio_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperienceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperienceCreateRequest) ProtoMessage() {}

func (x *ExperienceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperienceCreateRequest.ProtoReflect.Descriptor instead.
func (*ExperienceCreateRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{15}
}

func (x *ExperienceCreateRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ExperienceCreateRequest) GetPositions() []*PositionCreate {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *ExperienceCreateRequest) GetTechnologies() []int32 {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *ExperienceCreateRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

type ExperienceUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Positions     []*PositionUpdate      `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions,omitempty"`
	Technologies  []int32                `protobuf:"varint,5,rep,packed,name=technologies,proto3" json:"technologies,omitempty"`
	Company       string                 `protobuf:"bytes,6,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperienceUpdateRequest) Reset() {
	*x = ExperienceUpdateRequest{}
	mi := &file_portfolio_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperienceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperienceUpdateRequest) ProtoMessage() {}

func (x *ExperienceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperienceUpdateRequest.ProtoReflect.Descriptor instead.
func (*ExperienceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{16}
}

func (x *ExperienceUpdateRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ExperienceUpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExperienceUpdateRequest) GetPositions() []*PositionUpdate {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *ExperienceUpdateRequest) GetTechnologies() []int32 {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *ExperienceUpdateRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Message       []string               `protobuf:"bytes,4,rep,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_portfolio_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{17}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Message) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Message) GetMessage() []string {
	if x != nil {
		return x.Message
	}
	return nil
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_portfolio_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{18}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_portfolio_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteMessageRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_portfolio_proto protoreflect.FileDescriptor

const file_portfolio_proto_rawDesc = "" +
	"\n" +
	"\x0fportfolio.proto\x12\amanager\x1a\x1bbuf/validate/validate.proto\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x01\n" +
	"\n" +
	"Technology\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12,\n" +
	"\x12fallback_image_url\x18\x04 \x01(\tR\x10fallbackImageUrl\x127\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x1b.manager.TechnologyCategoryR\bcategory\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x82\x01\n" +
	"\x11TechnologySummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12,\n" +
	"\x12fallback_image_url\x18\x04 \x01(\tR\x10fallbackImageUrl\"R\n" +
	"\x17GetTechnologiesResponse\x127\n" +
	"\ftechnologies\x18\x01 \x03(\v2\x13.manager.TechnologyR\ftechnologies\"\xef\x01\n" +
	"\x17TechnologyCreateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12$\n" +
	"\timage_url\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bimageUrl\x125\n" +
	"\x12fallback_image_url\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x10fallbackImageUrl\x12A\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x1b.manager.TechnologyCategoryB\b\xbaH\x05\x82\x01\x02\x10\x01R\bcategory\"\x88\x02\n" +
	"\x17TechnologyUpdateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\x02id\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x02id\x12\x1b\n" +
	"\x04name\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12$\n" +
	"\timage_url\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bimageUrl\x125\n" +
	"\x12fallback_image_url\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x10fallbackImageUrl\x12A\n" +
	"\bcategory\x18\x06 \x01(\x0e2\x1b.manager.TechnologyCategoryB\b\xbaH\x05\x82\x01\x02\x10\x01R\bcategory\"\xec\x02\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12$\n" +
	"\vproject_url\x18\x05 \x01(\tH\x00R\n" +
	"projectUrl\x88\x01\x01\x12\"\n" +
	"\n" +
	"github_url\x18\x06 \x01(\tH\x01R\tgithubUrl\x88\x01\x01\x12>\n" +
	"\ftechnologies\x18\a \x03(\v2\x1a.manager.TechnologySummaryR\ftechnologies\x12\x1a\n" +
	"\bfeatured\x18\b \x01(\bR\bfeatured\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_project_urlB\r\n" +
	"\v_github_url\"4\n" +
	"\x0eProjectSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"C\n" +
	"\x13GetProjectsResponse\x12,\n" +
	"\bprojects\x18\x01 \x03(\v2\x10.manager.ProjectR\bprojects\"\xf1\x02\n" +
	"\x14ProjectCreateRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06userId\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12)\n" +
	"\vdescription\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vdescription\x12$\n" +
	"\timage_url\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bimageUrl\x12.\n" +
	"\vproject_url\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x88\x01\x01H\x00R\n" +
	"projectUrl\x88\x01\x01\x12,\n" +
	"\n" +
	"github_url\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x88\x01\x01H\x01R\tgithubUrl\x88\x01\x01\x120\n" +
	"\ftechnologies\x18\a \x03(\x05B\f\xbaH\t\x92\x01\x06\"\x04\x1a\x02 \x00R\ftechnologies\x12\x1a\n" +
	"\bfeatured\x18\b \x01(\bR\bfeaturedB\x0e\n" +
	"\f_project_urlB\r\n" +
	"\v_github_url\"\x8a\x03\n" +
	"\x14ProjectUpdateRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06userId\x12\x17\n" +
	"\x02id\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x02id\x12\x1b\n" +
	"\x04name\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12)\n" +
	"\vdescription\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vdescription\x12$\n" +
	"\timage_url\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bimageUrl\x12.\n" +
	"\vproject_url\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x88\x01\x01H\x00R\n" +
	"projectUrl\x88\x01\x01\x12,\n" +
	"\n" +
	"github_url\x18\a \x01(\tB\b\xbaH\x05r\x03\x88\x01\x01H\x01R\tgithubUrl\x88\x01\x01\x120\n" +
	"\ftechnologies\x18\b \x03(\x05B\f\xbaH\t\x92\x01\x06\"\x04\x1a\x02 \x00R\ftechnologies\x12\x1a\n" +
	"\bfeatured\x18\t \x01(\bR\bfeaturedB\x0e\n" +
	"\f_project_urlB\r\n" +
	"\v_github_url\"\xa8\x01\n" +
	"\bPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x14\n" +
	"\x05start\x18\x03 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\tR\x03end\x12\x1b\n" +
	"\twork_done\x18\x05 \x01(\tR\bworkDone\x123\n" +
	"\bprojects\x18\x06 \x03(\v2\x17.manager.ProjectSummaryR\bprojects\"\xdd\x01\n" +
	"\x0ePositionCreate\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06userId\x12\x1b\n" +
	"\x04role\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04role\x12\x1d\n" +
	"\x05start\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05start\x12\x15\n" +
	"\x03end\x18\x04 \x01(\tH\x00R\x03end\x88\x01\x01\x12$\n" +
	"\twork_done\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bworkDone\x12(\n" +
	"\bprojects\x18\x06 \x03(\x05B\f\xbaH\t\x92\x01\x06\"\x04\x1a\x02 \x00R\bprojectsB\x06\n" +
	"\x04_end\"\x9d\x02\n" +
	"\x0ePositionUpdate\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06userId\x12\x17\n" +
	"\x02id\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x02id\x12\x1a\n" +
	"\x06new_id\x18\x03 \x01(\tH\x00R\x05newId\x88\x01\x01\x12\x1b\n" +
	"\x04role\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04role\x12\x1d\n" +
	"\x05start\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05start\x12\x15\n" +
	"\x03end\x18\x06 \x01(\tH\x01R\x03end\x88\x01\x01\x12$\n" +
	"\twork_done\x18\a \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bworkDone\x12(\n" +
	"\bprojects\x18\b \x03(\x05B\f\xbaH\t\x92\x01\x06\"\x04\x1a\x02 \x00R\bprojectsB\t\n" +
	"\a_new_idB\x06\n" +
	"\x04_end\"\xa2\x02\n" +
	"\n" +
	"Experience\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x14\n" +
	"\x05start\x18\x03 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\tR\x03end\x12\x16\n" +
	"\x06tenure\x18\x05 \x01(\tR\x06tenure\x12/\n" +
	"\tpositions\x18\x06 \x03(\v2\x11.manager.PositionR\tpositions\x12>\n" +
	"\ftechnologies\x18\a \x03(\v2\x1a.manager.TechnologySummaryR\ftechnologies\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"O\n" +
	"\x16GetExperiencesResponse\x125\n" +
	"\vexperiences\x18\x01 \x03(\v2\x13.manager.ExperienceR\vexperiences\"\xd1\x01\n" +
	"\x17ExperienceCreateRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06userId\x12?\n" +
	"\tpositions\x18\x02 \x03(\v2\x17.manager.PositionCreateB\b\xbaH\x05\x92\x01\x02\b\x01R\tpositions\x120\n" +
	"\ftechnologies\x18\x04 \x03(\x05B\f\xbaH\t\x92\x01\x06\"\x04\x1a\x02 \x00R\ftechnologies\x12!\n" +
	"\acompany\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\acompany\"\xea\x01\n" +
	"\x17ExperienceUpdateRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06userId\x12\x17\n" +
	"\x02id\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x02id\x12?\n" +
	"\tpositions\x18\x03 \x03(\v2\x17.manager.PositionUpdateB\b\xbaH\x05\x92\x01\x02\b\x01R\tpositions\x120\n" +
	"\ftechnologies\x18\x05 \x03(\x05B\f\xbaH\t\x92\x01\x06\"\x04\x1a\x02 \x00R\ftechnologies\x12!\n" +
	"\acompany\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\acompany\"]\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x18\n" +
	"\amessage\x18\x04 \x03(\tR\amessage\"C\n" +
	"\x13GetMessagesResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.manager.MessageR\bmessages\"R\n" +
	"\x14DeleteMessageRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06userId\x12\x18\n" +
	"\x02id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id*\x99\x02\n" +
	"\x12TechnologyCategory\x12#\n" +
	"\x1fTECHNOLOGY_CATEGORY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cTECHNOLOGY_CATEGORY_FRONTEND\x10\x01\x12\x1f\n" +
	"\x1bTECHNOLOGY_CATEGORY_BACKEND\x10\x02\x12\x1a\n" +
	"\x16TECHNOLOGY_CATEGORY_DB\x10\x03\x12 \n" +
	"\x1cTECHNOLOGY_CATEGORY_LANGUAGE\x10\x04\x12\x1c\n" +
	"\x18TECHNOLOGY_CATEGORY_TOOL\x10\x05\x12!\n" +
	"\x1dTECHNOLOGY_CATEGORY_ACADEMICS\x10\x06\x12\x1c\n" +
	"\x18TECHNOLOGY_CATEGORY_NONE\x10\a2\x97\b\n" +
	"\x10PortfolioService\x12C\n" +
	"\vGetMessages\x12\x16.manager.SimpleRequest\x1a\x1c.manager.GetMessagesResponse\x12G\n" +
	"\rDeleteMessage\x12\x1d.manager.DeleteMessageRequest\x1a\x17.manager.SimpleResponse\x12K\n" +
	"\x0fGetTechnologies\x12\x16.manager.SimpleRequest\x1a .manager.GetTechnologiesResponse\x12M\n" +
	"\x10CreateTechnology\x12 .manager.TechnologyCreateRequest\x1a\x17.manager.SimpleResponse\x12M\n" +
	"\x10UpdateTechnology\x12 .manager.TechnologyUpdateRequest\x1a\x17.manager.SimpleResponse\x12C\n" +
	"\x10DeleteTechnology\x12\x16.manager.DeleteRequest\x1a\x17.manager.SimpleResponse\x12C\n" +
	"\vGetProjects\x12\x16.manager.SimpleRequest\x1a\x1c.manager.GetProjectsResponse\x12G\n" +
	"\rCreateProject\x12\x1d.manager.ProjectCreateRequest\x1a\x17.manager.SimpleResponse\x12G\n" +
	"\rUpdateProject\x12\x1d.manager.ProjectUpdateRequest\x1a\x17.manager.SimpleResponse\x12@\n" +
	"\rDeleteProject\x12\x16.manager.DeleteRequest\x1a\x17.manager.SimpleResponse\x12I\n" +
	"\x0eGetExperiences\x12\x16.manager.SimpleRequest\x1a\x1f.manager.GetExperiencesResponse\x12M\n" +
	"\x10CreateExperience\x12 .manager.ExperienceCreateRequest\x1a\x17.manager.SimpleResponse\x12M\n" +
	"\x10UpdateExperience\x12 .manager.ExperienceUpdateRequest\x1a\x17.manager.SimpleResponse\x12C\n" +
	"\x10DeleteExperience\x12\x16.manager.DeleteRequest\x1a\x17.manager.SimpleResponseB<Z:github.com/Aditya-0011/common/contracts/go/manager;managerb\x06proto3"

var (
	file_portfolio_proto_rawDescOnce sync.Once
	file_portfolio_proto_rawDescData []byte
)

func file_portfolio_proto_rawDescGZIP() []byte {
	file_portfolio_proto_rawDescOnce.Do(func() {
		file_portfolio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_portfolio_proto_rawDesc), len(file_portfolio_proto_rawDesc)))
	})
	return file_portfolio_proto_rawDescData
}

var file_portfolio_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_portfolio_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_portfolio_proto_goTypes = []any{
	(TechnologyCategory)(0),         // 0: manager.TechnologyCategory
	(*Technology)(nil),              // 1: manager.Technology
	(*TechnologySummary)(nil),       // 2: manager.TechnologySummary
	(*GetTechnologiesResponse)(nil), // 3: manager.GetTechnologiesResponse
	(*TechnologyCreateRequest)(nil), // 4: manager.TechnologyCreateRequest
	(*TechnologyUpdateRequest)(nil), // 5: manager.TechnologyUpdateRequest
	(*Project)(nil),                 // 6: manager.Project
	(*ProjectSummary)(nil),          // 7: manager.ProjectSummary
	(*GetProjectsResponse)(nil),     // 8: manager.GetProjectsResponse
	(*ProjectCreateRequest)(nil),    // 9: manager.ProjectCreateRequest
	(*ProjectUpdateRequest)(nil),    // 10: manager.ProjectUpdateRequest
	(*Position)(nil),                // 11: manager.Position
	(*PositionCreate)(nil),          // 12: manager.PositionCreate
	(*PositionUpdate)(nil),          // 13: manager.PositionUpdate
	(*Experience)(nil),              // 14: manager.Experience
	(*GetExperiencesResponse)(nil),  // 15: manager.GetExperiencesResponse
	(*ExperienceCreateRequest)(nil), // 16: manager.ExperienceCreateRequest
	(*ExperienceUpdateRequest)(nil), // 17: manager.ExperienceUpdateRequest
	(*Message)(nil),                 // 18: manager.Message
	(*GetMessagesResponse)(nil),     // 19: manager.GetMessagesResponse
	(*DeleteMessageRequest)(nil),    // 20: manager.DeleteMessageRequest
	(*timestamppb.Timestamp)(nil),   // 21: google.protobuf.Timestamp
	(*SimpleRequest)(nil),           // 22: manager.SimpleRequest
	(*DeleteRequest)(nil),           // 23: manager.DeleteRequest
	(*SimpleResponse)(nil),          // 24: manager.SimpleResponse
}
var file_portfolio_proto_depIdxs = []int32{
	0,  // 0: manager.Technology.category:type_name -> manager.TechnologyCategory
	21, // 1: manager.Technology.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: manager.GetTechnologiesResponse.technologies:type_name -> manager.Technology
	0,  // 3: manager.TechnologyCreateRequest.category:type_name -> manager.TechnologyCategory
	0,  // 4: manager.TechnologyUpdateRequest.category:type_name -> manager.TechnologyCategory
	2,  // 5: manager.Project.technologies:type_name -> manager.TechnologySummary
	21, // 6: manager.Project.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 7: manager.GetProjectsResponse.projects:type_name -> manager.Project
	7,  // 8: manager.Position.projects:type_name -> manager.ProjectSummary
	11, // 9: manager.Experience.positions:type_name -> manager.Position
	2,  // 10: manager.Experience.technologies:type_name -> manager.TechnologySummary
	21, // 11: manager.Experience.updated_at:type_name -> google.protobuf.Timestamp
	14, // 12: manager.GetExperiencesResponse.experiences:type_name -> manager.Experience
	12, // 13: manager.ExperienceCreateRequest.positions:type_name -> manager.PositionCreate
	13, // 14: manager.ExperienceUpdateRequest.positions:type_name -> manager.PositionUpdate
	18, // 15: manager.GetMessagesResponse.messages:type_name -> manager.Message
	22, // 16: manager.PortfolioService.GetMessages:input_type -> manager.SimpleRequest
	20, // 17: manager.PortfolioService.DeleteMessage:input_type -> manager.DeleteMessageRequest
	22, // 18: manager.PortfolioService.GetTechnologies:input_type -> manager.SimpleRequest
	4,  // 19: manager.PortfolioService.CreateTechnology:input_type -> manager.TechnologyCreateRequest
	5,  // 20: manager.PortfolioService.UpdateTechnology:input_type -> manager.TechnologyUpdateRequest
	23, // 21: manager.PortfolioService.DeleteTechnology:input_type -> manager.DeleteRequest
	22, // 22: manager.PortfolioService.GetProjects:input_type -> manager.SimpleRequest
	9,  // 23: manager.PortfolioService.CreateProject:input_type -> manager.ProjectCreateRequest
	10, // 24: manager.PortfolioService.UpdateProject:input_type -> manager.ProjectUpdateRequest
	23, // 25: manager.PortfolioService.DeleteProject:input_type -> manager.DeleteRequest
	22, // 26: manager.PortfolioService.GetExperiences:input_type -> manager.SimpleRequest
	16, // 27: manager.PortfolioService.CreateExperience:input_type -> manager.ExperienceCreateRequest
	17, // 28: manager.PortfolioService.UpdateExperience:input_type -> manager.ExperienceUpdateRequest
	23, // 29: manager.PortfolioService.DeleteExperience:input_type -> manager.DeleteRequest
	19, // 30: manager.PortfolioService.GetMessages:output_type -> manager.GetMessagesResponse
	24, // 31: manager.PortfolioService.DeleteMessage:output_type -> manager.SimpleResponse
	3,  // 32: manager.PortfolioService.GetTechnologies:output_type -> manager.GetTechnologiesResponse
	24, // 33: manager.PortfolioService.CreateTechnology:output_type -> manager.SimpleResponse
	24, // 34: manager.PortfolioService.UpdateTechnology:output_type -> manager.SimpleResponse
	24, // 35: manager.PortfolioService.DeleteTechnology:output_type -> manager.SimpleResponse
	8,  // 36: manager.PortfolioService.GetProjects:output_type -> manager.GetProjectsResponse
	24, // 37: manager.PortfolioService.CreateProject:output_type -> manager.SimpleResponse
	24, // 38: manager.PortfolioService.UpdateProject:output_type -> manager.SimpleResponse
	24, // 39: manager.PortfolioService.DeleteProject:output_type -> manager.SimpleResponse
	15, // 40: manager.PortfolioService.GetExperiences:output_type -> manager.GetExperiencesResponse
	24, // 41: manager.PortfolioService.CreateExperience:output_type -> manager.SimpleResponse
	24, // 42: manager.PortfolioService.UpdateExperience:output_type -> manager.SimpleResponse
	24, // 43: manager.PortfolioService.DeleteExperience:output_type -> manager.SimpleResponse
	30, // [30:44] is the sub-list for method output_type
	16, // [16:30] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_portfolio_proto_init() }
func file_portfolio_proto_init() {
	if File_portfolio_proto != nil {
		return
	}
	file_common_proto_init()
	file_portfolio_proto_msgTypes[5].OneofWrappers = []any{}
	file_portfolio_proto_msgTypes[8].OneofWrappers = []any{}
	file_portfolio_proto_msgTypes[9].OneofWrappers = []any{}
	file_portfolio_proto_msgTypes[11].OneofWrappers = []any{}
	file_portfolio_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_portfolio_proto_rawDesc), len(file_portfolio_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portfolio_proto_goTypes,
		DependencyIndexes: file_portfolio_proto_depIdxs,
		EnumInfos:         file_portfolio_proto_enumTypes,
		MessageInfos:      file_portfolio_proto_msgTypes,
	}.Build()
	File_portfolio_proto = out.File
	file_portfolio_proto_goTypes = nil
	file_portfolio_proto_depIdxs = nil
}
