// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: manager/portfolio.proto

package manager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PortfolioService_GetMessages_FullMethodName      = "/manager.PortfolioService/GetMessages"
	PortfolioService_AddMessage_FullMethodName       = "/manager.PortfolioService/AddMessage"
	PortfolioService_DeleteMessage_FullMethodName    = "/manager.PortfolioService/DeleteMessage"
	PortfolioService_GetTechnologies_FullMethodName  = "/manager.PortfolioService/GetTechnologies"
	PortfolioService_CreateTechnology_FullMethodName = "/manager.PortfolioService/CreateTechnology"
	PortfolioService_UpdateTechnology_FullMethodName = "/manager.PortfolioService/UpdateTechnology"
	PortfolioService_DeleteTechnology_FullMethodName = "/manager.PortfolioService/DeleteTechnology"
	PortfolioService_GetProjects_FullMethodName      = "/manager.PortfolioService/GetProjects"
	PortfolioService_CreateProject_FullMethodName    = "/manager.PortfolioService/CreateProject"
	PortfolioService_UpdateProject_FullMethodName    = "/manager.PortfolioService/UpdateProject"
	PortfolioService_DeleteProject_FullMethodName    = "/manager.PortfolioService/DeleteProject"
	PortfolioService_GetExperiences_FullMethodName   = "/manager.PortfolioService/GetExperiences"
	PortfolioService_CreateExperience_FullMethodName = "/manager.PortfolioService/CreateExperience"
	PortfolioService_UpdateExperience_FullMethodName = "/manager.PortfolioService/UpdateExperience"
	PortfolioService_DeleteExperience_FullMethodName = "/manager.PortfolioService/DeleteExperience"
)

// PortfolioServiceClient is the client API for PortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortfolioServiceClient interface {
	GetMessages(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	AddMessage(ctx context.Context, in *AddMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	GetTechnologies(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*GetTechnologiesResponse, error)
	CreateTechnology(ctx context.Context, in *TechnologyCreateRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UpdateTechnology(ctx context.Context, in *TechnologyUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	DeleteTechnology(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	GetProjects(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error)
	CreateProject(ctx context.Context, in *ProjectCreateRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UpdateProject(ctx context.Context, in *ProjectUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	DeleteProject(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	GetExperiences(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*GetExperiencesResponse, error)
	CreateExperience(ctx context.Context, in *ExperienceCreateRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	UpdateExperience(ctx context.Context, in *ExperienceUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	DeleteExperience(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
}

type portfolioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortfolioServiceClient(cc grpc.ClientConnInterface) PortfolioServiceClient {
	return &portfolioServiceClient{cc}
}

func (c *portfolioServiceClient) GetMessages(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) AddMessage(ctx context.Context, in *AddMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, PortfolioService_AddMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, PortfolioService_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetTechnologies(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*GetTechnologiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTechnologiesResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetTechnologies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CreateTechnology(ctx context.Context, in *TechnologyCreateRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, PortfolioService_CreateTechnology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) UpdateTechnology(ctx context.Context, in *TechnologyUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, PortfolioService_UpdateTechnology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) DeleteTechnology(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, PortfolioService_DeleteTechnology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetProjects(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CreateProject(ctx context.Context, in *ProjectCreateRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, PortfolioService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) UpdateProject(ctx context.Context, in *ProjectUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, PortfolioService_UpdateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) DeleteProject(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, PortfolioService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetExperiences(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*GetExperiencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExperiencesResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetExperiences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CreateExperience(ctx context.Context, in *ExperienceCreateRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, PortfolioService_CreateExperience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) UpdateExperience(ctx context.Context, in *ExperienceUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, PortfolioService_UpdateExperience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) DeleteExperience(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, PortfolioService_DeleteExperience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortfolioServiceServer is the server API for PortfolioService service.
// All implementations must embed UnimplementedPortfolioServiceServer
// for forward compatibility.
type PortfolioServiceServer interface {
	GetMessages(context.Context, *SimpleRequest) (*GetMessagesResponse, error)
	AddMessage(context.Context, *AddMessageRequest) (*SimpleResponse, error)
	DeleteMessage(context.Context, *DeleteMessageRequest) (*SimpleResponse, error)
	GetTechnologies(context.Context, *SimpleRequest) (*GetTechnologiesResponse, error)
	CreateTechnology(context.Context, *TechnologyCreateRequest) (*SimpleResponse, error)
	UpdateTechnology(context.Context, *TechnologyUpdateRequest) (*SimpleResponse, error)
	DeleteTechnology(context.Context, *DeleteRequest) (*SimpleResponse, error)
	GetProjects(context.Context, *SimpleRequest) (*GetProjectsResponse, error)
	CreateProject(context.Context, *ProjectCreateRequest) (*SimpleResponse, error)
	UpdateProject(context.Context, *ProjectUpdateRequest) (*SimpleResponse, error)
	DeleteProject(context.Context, *DeleteRequest) (*SimpleResponse, error)
	GetExperiences(context.Context, *SimpleRequest) (*GetExperiencesResponse, error)
	CreateExperience(context.Context, *ExperienceCreateRequest) (*SimpleResponse, error)
	UpdateExperience(context.Context, *ExperienceUpdateRequest) (*SimpleResponse, error)
	DeleteExperience(context.Context, *DeleteRequest) (*SimpleResponse, error)
	mustEmbedUnimplementedPortfolioServiceServer()
}

// UnimplementedPortfolioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortfolioServiceServer struct{}

func (UnimplementedPortfolioServiceServer) GetMessages(context.Context, *SimpleRequest) (*GetMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedPortfolioServiceServer) AddMessage(context.Context, *AddMessageRequest) (*SimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMessage not implemented")
}
func (UnimplementedPortfolioServiceServer) DeleteMessage(context.Context, *DeleteMessageRequest) (*SimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedPortfolioServiceServer) GetTechnologies(context.Context, *SimpleRequest) (*GetTechnologiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTechnologies not implemented")
}
func (UnimplementedPortfolioServiceServer) CreateTechnology(context.Context, *TechnologyCreateRequest) (*SimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTechnology not implemented")
}
func (UnimplementedPortfolioServiceServer) UpdateTechnology(context.Context, *TechnologyUpdateRequest) (*SimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTechnology not implemented")
}
func (UnimplementedPortfolioServiceServer) DeleteTechnology(context.Context, *DeleteRequest) (*SimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTechnology not implemented")
}
func (UnimplementedPortfolioServiceServer) GetProjects(context.Context, *SimpleRequest) (*GetProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjects not implemented")
}
func (UnimplementedPortfolioServiceServer) CreateProject(context.Context, *ProjectCreateRequest) (*SimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedPortfolioServiceServer) UpdateProject(context.Context, *ProjectUpdateRequest) (*SimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProject not implemented")
}
func (UnimplementedPortfolioServiceServer) DeleteProject(context.Context, *DeleteRequest) (*SimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedPortfolioServiceServer) GetExperiences(context.Context, *SimpleRequest) (*GetExperiencesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExperiences not implemented")
}
func (UnimplementedPortfolioServiceServer) CreateExperience(context.Context, *ExperienceCreateRequest) (*SimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExperience not implemented")
}
func (UnimplementedPortfolioServiceServer) UpdateExperience(context.Context, *ExperienceUpdateRequest) (*SimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateExperience not implemented")
}
func (UnimplementedPortfolioServiceServer) DeleteExperience(context.Context, *DeleteRequest) (*SimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExperience not implemented")
}
func (UnimplementedPortfolioServiceServer) mustEmbedUnimplementedPortfolioServiceServer() {}
func (UnimplementedPortfolioServiceServer) testEmbeddedByValue()                          {}

// UnsafePortfolioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortfolioServiceServer will
// result in compilation errors.
type UnsafePortfolioServiceServer interface {
	mustEmbedUnimplementedPortfolioServiceServer()
}

func RegisterPortfolioServiceServer(s grpc.ServiceRegistrar, srv PortfolioServiceServer) {
	// If the following call panics, it indicates UnimplementedPortfolioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortfolioService_ServiceDesc, srv)
}

func _PortfolioService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetMessages(ctx, req.(*SimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_AddMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).AddMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_AddMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).AddMessage(ctx, req.(*AddMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetTechnologies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetTechnologies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetTechnologies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetTechnologies(ctx, req.(*SimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CreateTechnology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TechnologyCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CreateTechnology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CreateTechnology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CreateTechnology(ctx, req.(*TechnologyCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_UpdateTechnology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TechnologyUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).UpdateTechnology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_UpdateTechnology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).UpdateTechnology(ctx, req.(*TechnologyUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_DeleteTechnology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).DeleteTechnology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_DeleteTechnology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).DeleteTechnology(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetProjects(ctx, req.(*SimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CreateProject(ctx, req.(*ProjectCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_UpdateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).UpdateProject(ctx, req.(*ProjectUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).DeleteProject(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetExperiences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetExperiences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetExperiences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetExperiences(ctx, req.(*SimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CreateExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExperienceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CreateExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CreateExperience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CreateExperience(ctx, req.(*ExperienceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_UpdateExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExperienceUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).UpdateExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_UpdateExperience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).UpdateExperience(ctx, req.(*ExperienceUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_DeleteExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).DeleteExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_DeleteExperience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).DeleteExperience(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortfolioService_ServiceDesc is the grpc.ServiceDesc for PortfolioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortfolioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manager.PortfolioService",
	HandlerType: (*PortfolioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessages",
			Handler:    _PortfolioService_GetMessages_Handler,
		},
		{
			MethodName: "AddMessage",
			Handler:    _PortfolioService_AddMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _PortfolioService_DeleteMessage_Handler,
		},
		{
			MethodName: "GetTechnologies",
			Handler:    _PortfolioService_GetTechnologies_Handler,
		},
		{
			MethodName: "CreateTechnology",
			Handler:    _PortfolioService_CreateTechnology_Handler,
		},
		{
			MethodName: "UpdateTechnology",
			Handler:    _PortfolioService_UpdateTechnology_Handler,
		},
		{
			MethodName: "DeleteTechnology",
			Handler:    _PortfolioService_DeleteTechnology_Handler,
		},
		{
			MethodName: "GetProjects",
			Handler:    _PortfolioService_GetProjects_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _PortfolioService_CreateProject_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _PortfolioService_UpdateProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _PortfolioService_DeleteProject_Handler,
		},
		{
			MethodName: "GetExperiences",
			Handler:    _PortfolioService_GetExperiences_Handler,
		},
		{
			MethodName: "CreateExperience",
			Handler:    _PortfolioService_CreateExperience_Handler,
		},
		{
			MethodName: "UpdateExperience",
			Handler:    _PortfolioService_UpdateExperience_Handler,
		},
		{
			MethodName: "DeleteExperience",
			Handler:    _PortfolioService_DeleteExperience_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manager/portfolio.proto",
}
