// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user.proto

package manager

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	About         string                 `protobuf:"bytes,1,opt,name=about,proto3" json:"about,omitempty"`
	CoverImage    string                 `protobuf:"bytes,2,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailsResponse) Reset() {
	*x = GetUserDetailsResponse{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsResponse) ProtoMessage() {}

func (x *GetUserDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetUserDetailsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserDetailsResponse) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *GetUserDetailsResponse) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *GetUserDetailsResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type EditUserDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	About         string                 `protobuf:"bytes,2,opt,name=about,proto3" json:"about,omitempty"`
	CoverImage    string                 `protobuf:"bytes,3,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditUserDetailsRequest) Reset() {
	*x = EditUserDetailsRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditUserDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserDetailsRequest) ProtoMessage() {}

func (x *EditUserDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserDetailsRequest.ProtoReflect.Descriptor instead.
func (*EditUserDetailsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *EditUserDetailsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EditUserDetailsRequest) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *EditUserDetailsRequest) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\amanager\x1a\x1bbuf/validate/validate.proto\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n" +
	"\x16GetUserDetailsResponse\x12\x14\n" +
	"\x05about\x18\x01 \x01(\tR\x05about\x12\x1f\n" +
	"\vcover_image\x18\x02 \x01(\tR\n" +
	"coverImage\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x87\x01\n" +
	"\x16EditUserDetailsRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06userId\x12\x1d\n" +
	"\x05about\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05about\x12,\n" +
	"\vcover_image\x18\x03 \x01(\tB\v\xbaH\br\x06\x18\xfa\x01\x88\x01\x01R\n" +
	"coverImage2\xa5\x01\n" +
	"\vUserService\x12I\n" +
	"\x0eGetUserDetails\x12\x16.manager.SimpleRequest\x1a\x1f.manager.GetUserDetailsResponse\x12K\n" +
	"\x0fEditUserDetails\x12\x1f.manager.EditUserDetailsRequest\x1a\x17.manager.SimpleResponseB<Z:github.com/Aditya-0011/common/contracts/go/manager;managerb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_proto_goTypes = []any{
	(*GetUserDetailsResponse)(nil), // 0: manager.GetUserDetailsResponse
	(*EditUserDetailsRequest)(nil), // 1: manager.EditUserDetailsRequest
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
	(*SimpleRequest)(nil),          // 3: manager.SimpleRequest
	(*SimpleResponse)(nil),         // 4: manager.SimpleResponse
}
var file_user_proto_depIdxs = []int32{
	2, // 0: manager.GetUserDetailsResponse.updated_at:type_name -> google.protobuf.Timestamp
	3, // 1: manager.UserService.GetUserDetails:input_type -> manager.SimpleRequest
	1, // 2: manager.UserService.EditUserDetails:input_type -> manager.EditUserDetailsRequest
	0, // 3: manager.UserService.GetUserDetails:output_type -> manager.GetUserDetailsResponse
	4, // 4: manager.UserService.EditUserDetails:output_type -> manager.SimpleResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
