// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wallet/finance.proto

package wallet

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryType int32

const (
	CategoryType_CATEGORY_TYPE_UNSPECIFIED CategoryType = 0
	CategoryType_CATEGORY_TYPE_INCOME      CategoryType = 1
	CategoryType_CATEGORY_TYPE_EXPENSE     CategoryType = 2
)

// Enum value maps for CategoryType.
var (
	CategoryType_name = map[int32]string{
		0: "CATEGORY_TYPE_UNSPECIFIED",
		1: "CATEGORY_TYPE_INCOME",
		2: "CATEGORY_TYPE_EXPENSE",
	}
	CategoryType_value = map[string]int32{
		"CATEGORY_TYPE_UNSPECIFIED": 0,
		"CATEGORY_TYPE_INCOME":      1,
		"CATEGORY_TYPE_EXPENSE":     2,
	}
)

func (x CategoryType) Enum() *CategoryType {
	p := new(CategoryType)
	*p = x
	return p
}

func (x CategoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CategoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_wallet_finance_proto_enumTypes[0].Descriptor()
}

func (CategoryType) Type() protoreflect.EnumType {
	return &file_wallet_finance_proto_enumTypes[0]
}

func (x CategoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CategoryType.Descriptor instead.
func (CategoryType) EnumDescriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{0}
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Type          CategoryType           `protobuf:"varint,4,opt,name=type,proto3,enum=wallet.CategoryType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_wallet_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Category) GetType() CategoryType {
	if x != nil {
		return x.Type
	}
	return CategoryType_CATEGORY_TYPE_UNSPECIFIED
}

func (x *Category) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Category) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CategorySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Type          CategoryType           `protobuf:"varint,4,opt,name=type,proto3,enum=wallet.CategoryType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategorySummary) Reset() {
	*x = CategorySummary{}
	mi := &file_wallet_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorySummary) ProtoMessage() {}

func (x *CategorySummary) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorySummary.ProtoReflect.Descriptor instead.
func (*CategorySummary) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{1}
}

func (x *CategorySummary) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategorySummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategorySummary) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CategorySummary) GetType() CategoryType {
	if x != nil {
		return x.Type
	}
	return CategoryType_CATEGORY_TYPE_UNSPECIFIED
}

type GetCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_wallet_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{2}
}

func (x *GetCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Type          CategoryType           `protobuf:"varint,4,opt,name=type,proto3,enum=wallet.CategoryType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_wallet_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCategoryRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateCategoryRequest) GetType() CategoryType {
	if x != nil {
		return x.Type
	}
	return CategoryType_CATEGORY_TYPE_UNSPECIFIED
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Type          CategoryType           `protobuf:"varint,5,opt,name=type,proto3,enum=wallet.CategoryType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_wallet_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCategoryRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCategoryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateCategoryRequest) GetType() CategoryType {
	if x != nil {
		return x.Type
	}
	return CategoryType_CATEGORY_TYPE_UNSPECIFIED
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Amount        *decimal.Decimal       `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      *CategorySummary       `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_wallet_finance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{5}
}

func (x *Transaction) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetAmount() *decimal.Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Transaction) GetCategory() *CategorySummary {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_wallet_finance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Amount        *decimal.Decimal       `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_wallet_finance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTransactionRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTransactionRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() *decimal.Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

type UpdateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Amount        *decimal.Decimal       `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_wallet_finance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTransactionRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTransactionRequest) GetAmount() *decimal.Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

type ExportTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTransactionsRequest) Reset() {
	*x = ExportTransactionsRequest{}
	mi := &file_wallet_finance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTransactionsRequest) ProtoMessage() {}

func (x *ExportTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ExportTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{9}
}

func (x *ExportTransactionsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ExportTransactionsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type ExportTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTransactionsResponse) Reset() {
	*x = ExportTransactionsResponse{}
	mi := &file_wallet_finance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTransactionsResponse) ProtoMessage() {}

func (x *ExportTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ExportTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{10}
}

func (x *ExportTransactionsResponse) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *ExportTransactionsResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ExportTransactionsResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type TransactionsUpdateHistory struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PreviousCategory    *CategorySummary       `protobuf:"bytes,2,opt,name=previous_category,json=previousCategory,proto3" json:"previous_category,omitempty"`
	CurrentCategory     *CategorySummary       `protobuf:"bytes,3,opt,name=current_category,json=currentCategory,proto3" json:"current_category,omitempty"`
	PreviousDescription string                 `protobuf:"bytes,4,opt,name=previous_description,json=previousDescription,proto3" json:"previous_description,omitempty"`
	CurrentDescription  string                 `protobuf:"bytes,5,opt,name=current_description,json=currentDescription,proto3" json:"current_description,omitempty"`
	PreviousAmount      *decimal.Decimal       `protobuf:"bytes,6,opt,name=previous_amount,json=previousAmount,proto3" json:"previous_amount,omitempty"`
	CurrentAmount       *decimal.Decimal       `protobuf:"bytes,7,opt,name=current_amount,json=currentAmount,proto3" json:"current_amount,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TransactionsUpdateHistory) Reset() {
	*x = TransactionsUpdateHistory{}
	mi := &file_wallet_finance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsUpdateHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsUpdateHistory) ProtoMessage() {}

func (x *TransactionsUpdateHistory) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsUpdateHistory.ProtoReflect.Descriptor instead.
func (*TransactionsUpdateHistory) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{11}
}

func (x *TransactionsUpdateHistory) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionsUpdateHistory) GetPreviousCategory() *CategorySummary {
	if x != nil {
		return x.PreviousCategory
	}
	return nil
}

func (x *TransactionsUpdateHistory) GetCurrentCategory() *CategorySummary {
	if x != nil {
		return x.CurrentCategory
	}
	return nil
}

func (x *TransactionsUpdateHistory) GetPreviousDescription() string {
	if x != nil {
		return x.PreviousDescription
	}
	return ""
}

func (x *TransactionsUpdateHistory) GetCurrentDescription() string {
	if x != nil {
		return x.CurrentDescription
	}
	return ""
}

func (x *TransactionsUpdateHistory) GetPreviousAmount() *decimal.Decimal {
	if x != nil {
		return x.PreviousAmount
	}
	return nil
}

func (x *TransactionsUpdateHistory) GetCurrentAmount() *decimal.Decimal {
	if x != nil {
		return x.CurrentAmount
	}
	return nil
}

func (x *TransactionsUpdateHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetTransactionsUpdateHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionId int32                  `protobuf:"varint,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsUpdateHistoryRequest) Reset() {
	*x = GetTransactionsUpdateHistoryRequest{}
	mi := &file_wallet_finance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsUpdateHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsUpdateHistoryRequest) ProtoMessage() {}

func (x *GetTransactionsUpdateHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsUpdateHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsUpdateHistoryRequest) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{12}
}

func (x *GetTransactionsUpdateHistoryRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTransactionsUpdateHistoryRequest) GetTransactionId() int32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type GetTransactionsUpdateHistoryResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	History       []*TransactionsUpdateHistory `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsUpdateHistoryResponse) Reset() {
	*x = GetTransactionsUpdateHistoryResponse{}
	mi := &file_wallet_finance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsUpdateHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsUpdateHistoryResponse) ProtoMessage() {}

func (x *GetTransactionsUpdateHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_finance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsUpdateHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsUpdateHistoryResponse) Descriptor() ([]byte, []int) {
	return file_wallet_finance_proto_rawDescGZIP(), []int{13}
}

func (x *GetTransactionsUpdateHistoryResponse) GetHistory() []*TransactionsUpdateHistory {
	if x != nil {
		return x.History
	}
	return nil
}

var File_wallet_finance_proto protoreflect.FileDescriptor

const file_wallet_finance_proto_rawDesc = "" +
	"\n" +
	"\x14wallet/finance.proto\x12\x06wallet\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/type/decimal.proto\x1a\x13wallet/common.proto\"\xe2\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.wallet.CategoryTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"s\n" +
	"\x0fCategorySummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.wallet.CategoryTypeR\x04type\"I\n" +
	"\x15GetCategoriesResponse\x120\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x10.wallet.CategoryR\n" +
	"categories\"\x87\x02\n" +
	"\x15CreateCategoryRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06userId\x12\x1e\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12x\n" +
	"\x04icon\x18\x03 \x01(\tBd\xbaHar_2]^[\\x{1F300}-\\x{1FAD6}\\x{2600}-\\x{26FF}\\x{2700}-\\x{27BF}\\x{1F1E6}-\\x{1F1FF}\\x{200D}\\x{FE0F}]+$R\x04icon\x122\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.wallet.CategoryTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04type\"\xa0\x02\n" +
	"\x15UpdateCategoryRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06userId\x12\x17\n" +
	"\x02id\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x02id\x12\x1e\n" +
	"\x04name\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12x\n" +
	"\x04icon\x18\x04 \x01(\tBd\xbaHar_2]^[\\x{1F300}-\\x{1FAD6}\\x{2600}-\\x{26FF}\\x{2700}-\\x{27BF}\\x{1F1E6}-\\x{1F1FF}\\x{200D}\\x{FE0F}]+$R\x04icon\x122\n" +
	"\x04type\x18\x05 \x01(\x0e2\x14.wallet.CategoryTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04type\"\x98\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12,\n" +
	"\x06amount\x18\x03 \x01(\v2\x14.google.type.DecimalR\x06amount\x123\n" +
	"\bcategory\x18\x04 \x01(\v2\x17.wallet.CategorySummaryR\bcategory\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"R\n" +
	"\x17GetTransactionsResponse\x127\n" +
	"\ftransactions\x18\x01 \x03(\v2\x13.wallet.TransactionR\ftransactions\"\x97\x02\n" +
	"\x18CreateTransactionRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06userId\x12(\n" +
	"\vcategory_id\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\n" +
	"categoryId\x12,\n" +
	"\vdescription\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\vdescription\x12\x80\x01\n" +
	"\x06amount\x18\x04 \x01(\v2\x14.google.type.DecimalBR\xbaHO\xba\x01L\n" +
	"\x0eamount_gt_zero\x12 amount must be greater than zero\x1a\x18double(this.value) > 0.0R\x06amount\"\xb0\x02\n" +
	"\x18UpdateTransactionRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06userId\x12(\n" +
	"\vcategory_id\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\n" +
	"categoryId\x12\x17\n" +
	"\x02id\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x02id\x12,\n" +
	"\vdescription\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\vdescription\x12\x80\x01\n" +
	"\x06amount\x18\x05 \x01(\v2\x14.google.type.DecimalBR\xbaHO\xba\x01L\n" +
	"\x0eamount_gt_zero\x12 amount must be greater than zero\x1a\x18double(this.value) > 0.0R\x06amount\"\x87\x02\n" +
	"\x19ExportTransactionsRequest\x12A\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tstartDate\x12=\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\aendDate:h\xbaHe\x1ac\n" +
	"\x10date_range_valid\x12-end date must be after or equal to start date\x1a this.end_date >= this.start_date\"y\n" +
	"\x1aExportTransactionsResponse\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"\xd0\x03\n" +
	"\x19TransactionsUpdateHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12D\n" +
	"\x11previous_category\x18\x02 \x01(\v2\x17.wallet.CategorySummaryR\x10previousCategory\x12B\n" +
	"\x10current_category\x18\x03 \x01(\v2\x17.wallet.CategorySummaryR\x0fcurrentCategory\x121\n" +
	"\x14previous_description\x18\x04 \x01(\tR\x13previousDescription\x12/\n" +
	"\x13current_description\x18\x05 \x01(\tR\x12currentDescription\x12=\n" +
	"\x0fprevious_amount\x18\x06 \x01(\v2\x14.google.type.DecimalR\x0epreviousAmount\x12;\n" +
	"\x0ecurrent_amount\x18\a \x01(\v2\x14.google.type.DecimalR\rcurrentAmount\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"w\n" +
	"#GetTransactionsUpdateHistoryRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x06userId\x12.\n" +
	"\x0etransaction_id\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\rtransactionId\"c\n" +
	"$GetTransactionsUpdateHistoryResponse\x12;\n" +
	"\ahistory\x18\x01 \x03(\v2!.wallet.TransactionsUpdateHistoryR\ahistory*b\n" +
	"\fCategoryType\x12\x1d\n" +
	"\x19CATEGORY_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CATEGORY_TYPE_INCOME\x10\x01\x12\x19\n" +
	"\x15CATEGORY_TYPE_EXPENSE\x10\x022\xaf\x06\n" +
	"\x0eFinanceService\x12E\n" +
	"\rGetCategories\x12\x15.wallet.SimpleRequest\x1a\x1d.wallet.GetCategoriesResponse\x12G\n" +
	"\x0eCreateCategory\x12\x1d.wallet.CreateCategoryRequest\x1a\x16.wallet.SimpleResponse\x12G\n" +
	"\x0eUpdateCategory\x12\x1d.wallet.UpdateCategoryRequest\x1a\x16.wallet.SimpleResponse\x12?\n" +
	"\x0eDeleteCategory\x12\x15.wallet.DeleteRequest\x1a\x16.wallet.SimpleResponse\x12I\n" +
	"\x0fGetTransactions\x12\x15.wallet.SimpleRequest\x1a\x1f.wallet.GetTransactionsResponse\x12M\n" +
	"\x11CreateTransaction\x12 .wallet.CreateTransactionRequest\x1a\x16.wallet.SimpleResponse\x12M\n" +
	"\x11UpdateTransaction\x12 .wallet.UpdateTransactionRequest\x1a\x16.wallet.SimpleResponse\x12B\n" +
	"\x11DeleteTransaction\x12\x15.wallet.DeleteRequest\x1a\x16.wallet.SimpleResponse\x12[\n" +
	"\x12ExportTransactions\x12!.wallet.ExportTransactionsRequest\x1a\".wallet.ExportTransactionsResponse\x12y\n" +
	"\x1cGetTransactionsUpdateHistory\x12+.wallet.GetTransactionsUpdateHistoryRequest\x1a,.wallet.GetTransactionsUpdateHistoryResponseBCZ8github.com/Aditya-0011/common/contracts/go/wallet;wallet\xaa\x02\x06Walletb\x06proto3"

var (
	file_wallet_finance_proto_rawDescOnce sync.Once
	file_wallet_finance_proto_rawDescData []byte
)

func file_wallet_finance_proto_rawDescGZIP() []byte {
	file_wallet_finance_proto_rawDescOnce.Do(func() {
		file_wallet_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_finance_proto_rawDesc), len(file_wallet_finance_proto_rawDesc)))
	})
	return file_wallet_finance_proto_rawDescData
}

var file_wallet_finance_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wallet_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_wallet_finance_proto_goTypes = []any{
	(CategoryType)(0),                            // 0: wallet.CategoryType
	(*Category)(nil),                             // 1: wallet.Category
	(*CategorySummary)(nil),                      // 2: wallet.CategorySummary
	(*GetCategoriesResponse)(nil),                // 3: wallet.GetCategoriesResponse
	(*CreateCategoryRequest)(nil),                // 4: wallet.CreateCategoryRequest
	(*UpdateCategoryRequest)(nil),                // 5: wallet.UpdateCategoryRequest
	(*Transaction)(nil),                          // 6: wallet.Transaction
	(*GetTransactionsResponse)(nil),              // 7: wallet.GetTransactionsResponse
	(*CreateTransactionRequest)(nil),             // 8: wallet.CreateTransactionRequest
	(*UpdateTransactionRequest)(nil),             // 9: wallet.UpdateTransactionRequest
	(*ExportTransactionsRequest)(nil),            // 10: wallet.ExportTransactionsRequest
	(*ExportTransactionsResponse)(nil),           // 11: wallet.ExportTransactionsResponse
	(*TransactionsUpdateHistory)(nil),            // 12: wallet.TransactionsUpdateHistory
	(*GetTransactionsUpdateHistoryRequest)(nil),  // 13: wallet.GetTransactionsUpdateHistoryRequest
	(*GetTransactionsUpdateHistoryResponse)(nil), // 14: wallet.GetTransactionsUpdateHistoryResponse
	(*timestamppb.Timestamp)(nil),                // 15: google.protobuf.Timestamp
	(*decimal.Decimal)(nil),                      // 16: google.type.Decimal
	(*SimpleRequest)(nil),                        // 17: wallet.SimpleRequest
	(*DeleteRequest)(nil),                        // 18: wallet.DeleteRequest
	(*SimpleResponse)(nil),                       // 19: wallet.SimpleResponse
}
var file_wallet_finance_proto_depIdxs = []int32{
	0,  // 0: wallet.Category.type:type_name -> wallet.CategoryType
	15, // 1: wallet.Category.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: wallet.Category.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: wallet.CategorySummary.type:type_name -> wallet.CategoryType
	1,  // 4: wallet.GetCategoriesResponse.categories:type_name -> wallet.Category
	0,  // 5: wallet.CreateCategoryRequest.type:type_name -> wallet.CategoryType
	0,  // 6: wallet.UpdateCategoryRequest.type:type_name -> wallet.CategoryType
	16, // 7: wallet.Transaction.amount:type_name -> google.type.Decimal
	2,  // 8: wallet.Transaction.category:type_name -> wallet.CategorySummary
	15, // 9: wallet.Transaction.created_at:type_name -> google.protobuf.Timestamp
	15, // 10: wallet.Transaction.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 11: wallet.GetTransactionsResponse.transactions:type_name -> wallet.Transaction
	16, // 12: wallet.CreateTransactionRequest.amount:type_name -> google.type.Decimal
	16, // 13: wallet.UpdateTransactionRequest.amount:type_name -> google.type.Decimal
	15, // 14: wallet.ExportTransactionsRequest.start_date:type_name -> google.protobuf.Timestamp
	15, // 15: wallet.ExportTransactionsRequest.end_date:type_name -> google.protobuf.Timestamp
	2,  // 16: wallet.TransactionsUpdateHistory.previous_category:type_name -> wallet.CategorySummary
	2,  // 17: wallet.TransactionsUpdateHistory.current_category:type_name -> wallet.CategorySummary
	16, // 18: wallet.TransactionsUpdateHistory.previous_amount:type_name -> google.type.Decimal
	16, // 19: wallet.TransactionsUpdateHistory.current_amount:type_name -> google.type.Decimal
	15, // 20: wallet.TransactionsUpdateHistory.created_at:type_name -> google.protobuf.Timestamp
	12, // 21: wallet.GetTransactionsUpdateHistoryResponse.history:type_name -> wallet.TransactionsUpdateHistory
	17, // 22: wallet.FinanceService.GetCategories:input_type -> wallet.SimpleRequest
	4,  // 23: wallet.FinanceService.CreateCategory:input_type -> wallet.CreateCategoryRequest
	5,  // 24: wallet.FinanceService.UpdateCategory:input_type -> wallet.UpdateCategoryRequest
	18, // 25: wallet.FinanceService.DeleteCategory:input_type -> wallet.DeleteRequest
	17, // 26: wallet.FinanceService.GetTransactions:input_type -> wallet.SimpleRequest
	8,  // 27: wallet.FinanceService.CreateTransaction:input_type -> wallet.CreateTransactionRequest
	9,  // 28: wallet.FinanceService.UpdateTransaction:input_type -> wallet.UpdateTransactionRequest
	18, // 29: wallet.FinanceService.DeleteTransaction:input_type -> wallet.DeleteRequest
	10, // 30: wallet.FinanceService.ExportTransactions:input_type -> wallet.ExportTransactionsRequest
	13, // 31: wallet.FinanceService.GetTransactionsUpdateHistory:input_type -> wallet.GetTransactionsUpdateHistoryRequest
	3,  // 32: wallet.FinanceService.GetCategories:output_type -> wallet.GetCategoriesResponse
	19, // 33: wallet.FinanceService.CreateCategory:output_type -> wallet.SimpleResponse
	19, // 34: wallet.FinanceService.UpdateCategory:output_type -> wallet.SimpleResponse
	19, // 35: wallet.FinanceService.DeleteCategory:output_type -> wallet.SimpleResponse
	7,  // 36: wallet.FinanceService.GetTransactions:output_type -> wallet.GetTransactionsResponse
	19, // 37: wallet.FinanceService.CreateTransaction:output_type -> wallet.SimpleResponse
	19, // 38: wallet.FinanceService.UpdateTransaction:output_type -> wallet.SimpleResponse
	19, // 39: wallet.FinanceService.DeleteTransaction:output_type -> wallet.SimpleResponse
	11, // 40: wallet.FinanceService.ExportTransactions:output_type -> wallet.ExportTransactionsResponse
	14, // 41: wallet.FinanceService.GetTransactionsUpdateHistory:output_type -> wallet.GetTransactionsUpdateHistoryResponse
	32, // [32:42] is the sub-list for method output_type
	22, // [22:32] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_wallet_finance_proto_init() }
func file_wallet_finance_proto_init() {
	if File_wallet_finance_proto != nil {
		return
	}
	file_wallet_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_finance_proto_rawDesc), len(file_wallet_finance_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_finance_proto_goTypes,
		DependencyIndexes: file_wallet_finance_proto_depIdxs,
		EnumInfos:         file_wallet_finance_proto_enumTypes,
		MessageInfos:      file_wallet_finance_proto_msgTypes,
	}.Build()
	File_wallet_finance_proto = out.File
	file_wallet_finance_proto_goTypes = nil
	file_wallet_finance_proto_depIdxs = nil
}
