// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wallet/user.proto

package wallet

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllIncome     *decimal.Decimal       `protobuf:"bytes,1,opt,name=all_income,json=allIncome,proto3" json:"all_income,omitempty"`
	AllExpense    *decimal.Decimal       `protobuf:"bytes,2,opt,name=all_expense,json=allExpense,proto3" json:"all_expense,omitempty"`
	MonthIncome   *decimal.Decimal       `protobuf:"bytes,3,opt,name=month_income,json=monthIncome,proto3" json:"month_income,omitempty"`
	MonthExpense  *decimal.Decimal       `protobuf:"bytes,4,opt,name=month_expense,json=monthExpense,proto3" json:"month_expense,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSummaryResponse) Reset() {
	*x = GetUserSummaryResponse{}
	mi := &file_wallet_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSummaryResponse) ProtoMessage() {}

func (x *GetUserSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetUserSummaryResponse) Descriptor() ([]byte, []int) {
	return file_wallet_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserSummaryResponse) GetAllIncome() *decimal.Decimal {
	if x != nil {
		return x.AllIncome
	}
	return nil
}

func (x *GetUserSummaryResponse) GetAllExpense() *decimal.Decimal {
	if x != nil {
		return x.AllExpense
	}
	return nil
}

func (x *GetUserSummaryResponse) GetMonthIncome() *decimal.Decimal {
	if x != nil {
		return x.MonthIncome
	}
	return nil
}

func (x *GetUserSummaryResponse) GetMonthExpense() *decimal.Decimal {
	if x != nil {
		return x.MonthExpense
	}
	return nil
}

func (x *GetUserSummaryResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

var File_wallet_user_proto protoreflect.FileDescriptor

const file_wallet_user_proto_rawDesc = "" +
	"\n" +
	"\x11wallet/user.proto\x12\x06wallet\x1a\x19google/type/decimal.proto\x1a\x13wallet/common.proto\"\x97\x02\n" +
	"\x16GetUserSummaryResponse\x123\n" +
	"\n" +
	"all_income\x18\x01 \x01(\v2\x14.google.type.DecimalR\tallIncome\x125\n" +
	"\vall_expense\x18\x02 \x01(\v2\x14.google.type.DecimalR\n" +
	"allExpense\x127\n" +
	"\fmonth_income\x18\x03 \x01(\v2\x14.google.type.DecimalR\vmonthIncome\x129\n" +
	"\rmonth_expense\x18\x04 \x01(\v2\x14.google.type.DecimalR\fmonthExpense\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate2V\n" +
	"\vUserService\x12G\n" +
	"\x0eGetUserSummary\x12\x15.wallet.SimpleRequest\x1a\x1e.wallet.GetUserSummaryResponseBCZ8github.com/Aditya-0011/common/contracts/go/wallet;wallet\xaa\x02\x06Walletb\x06proto3"

var (
	file_wallet_user_proto_rawDescOnce sync.Once
	file_wallet_user_proto_rawDescData []byte
)

func file_wallet_user_proto_rawDescGZIP() []byte {
	file_wallet_user_proto_rawDescOnce.Do(func() {
		file_wallet_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_user_proto_rawDesc), len(file_wallet_user_proto_rawDesc)))
	})
	return file_wallet_user_proto_rawDescData
}

var file_wallet_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wallet_user_proto_goTypes = []any{
	(*GetUserSummaryResponse)(nil), // 0: wallet.GetUserSummaryResponse
	(*decimal.Decimal)(nil),        // 1: google.type.Decimal
	(*SimpleRequest)(nil),          // 2: wallet.SimpleRequest
}
var file_wallet_user_proto_depIdxs = []int32{
	1, // 0: wallet.GetUserSummaryResponse.all_income:type_name -> google.type.Decimal
	1, // 1: wallet.GetUserSummaryResponse.all_expense:type_name -> google.type.Decimal
	1, // 2: wallet.GetUserSummaryResponse.month_income:type_name -> google.type.Decimal
	1, // 3: wallet.GetUserSummaryResponse.month_expense:type_name -> google.type.Decimal
	2, // 4: wallet.UserService.GetUserSummary:input_type -> wallet.SimpleRequest
	0, // 5: wallet.UserService.GetUserSummary:output_type -> wallet.GetUserSummaryResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_wallet_user_proto_init() }
func file_wallet_user_proto_init() {
	if File_wallet_user_proto != nil {
		return
	}
	file_wallet_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_user_proto_rawDesc), len(file_wallet_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_user_proto_goTypes,
		DependencyIndexes: file_wallet_user_proto_depIdxs,
		MessageInfos:      file_wallet_user_proto_msgTypes,
	}.Build()
	File_wallet_user_proto = out.File
	file_wallet_user_proto_goTypes = nil
	file_wallet_user_proto_depIdxs = nil
}
