name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Buf Checks
        uses: bufbuild/buf-action@v1
        with:
          input: protos
          push: false
          format: false 

      - name: Generate Go Code
        run: buf generate protos --template protos/buf.gen.yaml
        
      - name: Update Go dependencies
        working-directory: contracts/go
        run: |
          go mod tidy

      # - name: Generate C# Code
      #   run: buf generate protos --template protos/buf.gen.csharp.yaml

      - name: Commit and push generated code
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add contracts/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: regenerate protobuf contracts"
            git push
          fi