name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-verify:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Buf Checks
        uses: bufbuild/buf-action@v1
        with:
          input: protos
          push: false
          format: false 

      - name: Generate Go Code
        run: buf generate protos --template protos/buf.gen.yaml
        
      # - name: Generate C# Code
      #   run: buf generate protos --template protos/buf.gen.csharp.yaml